using CairoMakie, Random, Distributions
CairoMakie.activate!(type = "svg") #hide
Random.seed!(1234)
b = Binomial(10, 0.85)
n = 500
function someSegments(; n = 50)
    Point2f.(vec([[x, rand(b)] for i in 1:2, x = rand(n)]))
end
linesegments(someSegments(; n = n);
    color = rand(n), 
    colormap = :Spectral_11, linewidth = abs.(randn(n)), 
    axis = (; xlabel = "x", ylabel = "y"),
    figure = (; resolution = (600,400))
    )
current_figure() #hide

# !!! warning 
# This example was autogenerated using:

using Pkg
Pkg.status(["CairoMakie"])